# Generated by Django 3.1.3 on 2020-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escolas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Escolas', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('tipo_Escolas', models.CharField(max_length=200)),
                ('conceito_Escolas', models.CharField(max_length=200)),
            ],
        ),
    ]
